### PR TITLE
Updated React.PropTypes - replaced with the "prop-types" library to support React 16

### LINKED ISSUE #5: React.PropTypes is no longer supported
This package is not supported on react 16 or newer

### PR DESCRIPTION
**Pull request by adamtal3**
Fixes #5

### CODE REVIEW

**Comment by adamtal3** [comment]
I've also added an "npm run clean" & "npm run build" scripts to support building on windows. (didn't touch the existing build scripts)

**Comment by adamtal3** [comment]
@miadwang - It seems the latest version is still not published to npm.
Can you publish `0.1.5` so everyone will have support for latest react versions?

Thanks.

**Comment by adamtal3** [comment]
@miadwang - Any chance of running "npm publish"? :)

I'm still using this with a github link but npm doesn't like it. If you can't publish it I can publish it under a different name to npm if you won't express opposition.

**Comment by miadwang** [comment]
Thank you for your suggestion.
I’ll make it work in a couple of days.

**Comment by adamtal3** [comment]
> I’ll make it work in a couple of days.

Any progress with the publish? 😃

**Comment by adamtal3** [comment]
Thank you!

**Pull request merged**
